# Task 3 : Iris Flower Classification

### Import Libraries: 

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


### Load the Dataset: Load the Iris dataset.

In [13]:
df = pd.read_csv('https://raw.githubusercontent.com/amankharwal/Website-data/master/IRIS.csv')
df.head()


sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### Splitting the dataset into Dependent and Independent Variables

In [14]:
X=df.drop('species',axis=1)
y=df['species']


### Splitting the dataset into Traning and Testing Data

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=101)

### K-Nearest Neighbors (KNN) algorithm as the classifier.

In [16]:
k = 3  # Number of neighbors
classifier = KNeighborsClassifier(n_neighbors=k)
classifier.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=3)

### Make Predictions: Use the trained model to make predictions on the test data.

In [17]:
y_pred = classifier.predict(X_test)


### Evaluate the Model: Assess the performance of the model using various evaluation metrics.

In [18]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nAccuracy:", accuracy_score(y_test, y_pred))


Confusion Matrix:
 [[10  0  0]
 [ 0 12  0]
 [ 0  0  8]]

Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00        12
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30


Accuracy: 1.0


### Train and evaluate the Logistic Regression classifier

In [19]:
from sklearn.linear_model import LogisticRegression

logreg_classifier = LogisticRegression(max_iter=1000)
logreg_classifier.fit(X_train, y_train)

logreg_y_pred = logreg_classifier.predict(X_test)

print("Logistic Regression Confusion Matrix:\n", confusion_matrix(y_test, logreg_y_pred))
print("\nLogistic Regression Classification Report:\n", classification_report(y_test, logreg_y_pred))
print("\nLogistic Regression Accuracy:", accuracy_score(y_test, logreg_y_pred))



Logistic Regression Confusion Matrix:
 [[10  0  0]
 [ 0 12  0]
 [ 0  0  8]]

Logistic Regression Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00        12
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30


Logistic Regression Accuracy: 1.0


### Support Vector Machine (SVM):

In [20]:
from sklearn.svm import SVC

svm_classifier = SVC(kernel='linear', C=1)
svm_classifier.fit(X_train, y_train)

svm_y_pred = svm_classifier.predict(X_test)

print("SVM Confusion Matrix:\n", confusion_matrix(y_test, svm_y_pred))
print("\nSVM Classification Report:\n", classification_report(y_test, svm_y_pred))
print("\nSVM Accuracy:", accuracy_score(y_test, svm_y_pred))


SVM Confusion Matrix:
 [[10  0  0]
 [ 0 12  0]
 [ 0  0  8]]

SVM Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00        12
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30


SVM Accuracy: 1.0


### Random Forest Classifier:

In [21]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

rf_y_pred = rf_classifier.predict(X_test)

print("Random Forest Confusion Matrix:\n", confusion_matrix(y_test, rf_y_pred))
print("\nRandom Forest Classification Report:\n", classification_report(y_test, rf_y_pred))
print("\nRandom Forest Accuracy:", accuracy_score(y_test, rf_y_pred))


Random Forest Confusion Matrix:
 [[10  0  0]
 [ 0 12  0]
 [ 0  1  7]]

Random Forest Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.92      1.00      0.96        12
 Iris-virginica       1.00      0.88      0.93         8

       accuracy                           0.97        30
      macro avg       0.97      0.96      0.96        30
   weighted avg       0.97      0.97      0.97        30


Random Forest Accuracy: 0.9666666666666667


### Conclusion : 

#### Logistic Regression model performs exceptionally well in classifying the Iris flowers into the respective species, as is evident from perfect accuracy and high values of precision and recall and f1-score for most cases.